### ISSUE TITLE
README.md refers to non-existent LICENSE.txt file.

### ISSUE THREAD

**Issue by kfogel** [Taskulu/deskulu#2]
At the bottom of README.md, it says the license is "GPLv2. See LICENSE.txt."  However, there is no LICENSE.txt at the top level of the tree.

(There are 50 interior LICENSE.txt files, under sites/all/modules/ and sites/all/themes/, but I assume those are all third-party license files -- they're not expressing the license for Deskulu as a whole work.)

**Comment by farhadhf** [comment]
Thanks, just added the license file.

**Comment by kfogel** [comment]
Thanks, @farhadhf.

**Comment by kfogel** [comment]
By the way, the Drupal GPL-2.0 licensing allows derivative works to be under GPL-3.0 if they want to be.  You might prefer v2 anyway, but if you chose it only because you thought you were bound to it, that isn't the case.  See https://www.drupal.org/about/licensing#q1 for more.  (Just mentioning it in case you would actually prefer GPLv3, or even moving to AGPL.)

Of course, any third-party modules might complicate things; I haven't looked closely into that.
