### ISSUE TITLE
email reply via ticket REST API call

### ISSUE THREAD

**Issue by vanous** [Taskulu/deskulu#3]
Hi all,

very nice looking project!

Reading the howto and not sure if this isn't a typo:

    When The Receiving Email Address Matches: ticket--@helpmail.yoursite.com
    Post To URL: http://yoursite.com/tickets/incoming/new

Shouldn't existing ticket go to different REST call?

Good luck!
cheers
P.

**Comment by farhadhf** [comment]
Hey, thanks! You're right. Just fixed it.

**Comment by farhadhf** [comment]
Also, please note that the correct email address to match is ticket-*-*@helpmail.yoursite.com.

**Comment by vanous** [comment]
Thanks!
We use JitBit Helpdesk and are happy, but I like this very much upon first look.

Cheers Petr
